# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(231, 324)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 0, 151, 31))
        self.label.setObjectName("label")
        self.id_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id_input.setGeometry(QtCore.QRect(50, 50, 141, 21))
        self.id_input.setObjectName("id_input")
        self.id_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(10, 50, 31, 16))
        self.id_label.setObjectName("id_label")
        self.label_candidate = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_candidate.setGeometry(QtCore.QRect(70, 90, 81, 21))
        self.label_candidate.setObjectName("label_candidate")
        self.radioButton_jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_jane.setGeometry(QtCore.QRect(80, 130, 71, 16))
        self.radioButton_jane.setObjectName("radioButton_jane")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_jane)
        self.radioButton_john = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_john.setGeometry(QtCore.QRect(80, 160, 61, 16))
        self.radioButton_john.setObjectName("radioButton_john")
        self.buttonGroup.addButton(self.radioButton_john)
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(40, 200, 151, 31))
        self.submit_button.setObjectName("submit_button")
        self.label_under_button = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_under_button.setGeometry(QtCore.QRect(40, 240, 121, 16))
        self.label_under_button.setText("")
        self.label_under_button.setObjectName("label_under_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 231, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "VOTING APPLICATION"))
        self.id_label.setText(_translate("MainWindow", "ID:"))
        self.label_candidate.setText(_translate("MainWindow", "CANDIDATES"))
        self.radioButton_jane.setText(_translate("MainWindow", "Jane"))
        self.radioButton_john.setText(_translate("MainWindow", "John"))
        self.submit_button.setText(_translate("MainWindow", "SUBMIT VOTE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
